LATEST_TYPE_WORDS={'latest', 'l'}
GROUPING_TYPE_WORDS={'grouping', 'g'}
SUM_TYPE_WORDS={'sum', 's'}
WEEKLY_REPORT_PAGE='1'
WEEKLY_REPORT_MAX_PAGE='50'
EXCEPTION_WEEKLY_REPORT_KEYWORDS= ['前へ', '後へ', '最初へ', '最後へ']
WEEKLY_REPORT_FIRST_PAGE='1'
